---

- name: 'Setup alsamixer'
  command: amixer cset numid=3 1 && amixer cset numid=1 100% && alsactl store

- name: 'Install open-jtalk'
  apt:
    name: open-jtalk
    state: present

- name: 'Install open-jtalk-mecab-naist-jdic'
  apt:
    name: open-jtalk-mecab-naist-jdic
    state: present

- name: 'Install hts-voice-nitech-jp-atr503-m001'
  apt:
    name: hts-voice-nitech-jp-atr503-m001
    state: present

- get_url:
    force: no
    url: http://downloads.sourceforge.net/project/mmdagent/MMDAgent_Example/MMDAgent_Example-1.6/MMDAgent_Example-1.6.zip
    dest: /tmp

- unarchive:
    remote_src: yes
    src: /tmp/MMDAgent_Example-1.6.zip
    dest: /tmp
    creates: /tmp/MMDAgent_Example-1.6/Voice/mei

- command: cp -R /tmp/MMDAgent_Example-1.6/Voice/mei /usr/share/hts-voice
  args:
    creates: /usr/share/hts-voice/mei

- name: 'Install jsay.sh for pi user'
  copy:
    src: jsay.sh
    dest: /home/pi/bin/jsay.sh
    owner: pi
    group: pi
    mode: 0755



